[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Nia-04/CSPC-513-ML-Lab/blob/main/Practical_02_Data_Preprocessing.ipynb)

# Practical 02: Data Preprocessing

## Aim
To demonstrate various data preprocessing techniques for a given dataset.

## INTRODUCTION

Data preprocessing is an important step in the data analysis and machine learning process. Real-world datasets may contain missing values, inconsistent entries, duplicate records, incorrect data types, and outliers.

In this practical, preprocessing techniques are applied to the given student performance dataset to improve its quality, consistency, and reliability before further analysis.

In [1]:
import os

if os.path.exists("DATASETS/Mldata.xlsx"):
    print("Dataset folder already available.")
else:
    !git clone https://github.com/Nia-04/CSPC-513-ML-Lab.git
    %cd CSPC-513-ML-Lab
    print("Repository cloned successfully.")

Dataset folder already available.

In [6]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_excel(
    "DATASETS/Mldata.xlsx",
    dtype={"ROLL NO.": "string"}
)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (86, 9)

## EXPLORE THE DATASET

The dataset is initially explored to understand its structure and contents.

The following information is examined:

- Number of rows and columns
- Column names
- Data types
- First few records
- Basic statistical information

This initial exploration helps identify possible data quality issues that need to be addressed during preprocessing.

In [9]:
print("First 5 rows:")
display(df.head())

print("\nDataset Information:")
df.info()

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

First 5 rows:

,ROLL NO.,GENDER,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT
0,240104010001,M,30.0,30.0,30.0,30.0,30.0,C,PASS
1,240104010002,F,30.0,40.0,45.0,40.0,35.0,B,Pass
2,240104010003,M,38.0,38.0,38.0,38.0,38.0,B,Pass
3,240104010004,M,59.0,55.0,57.0,58.0,54.0,A,pass
4,240104010005,M,30.0,30.0,30.0,30.0,30.0,C,Pass

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ROLL NO.           71 non-null     string
 1   GENDER             72 non-null     object
 2   SOFTWARE ENGINEER  68 non-null     float64
 3   TOC                68 non-null     float64
 4   COMPUTER NETWORK   68 non-null     float64
 5   MACHINE LEARNING   68 non-null     float64
 6   DATA WAREHOUSE     68 non-null     float64
 7   GRADE              67 non-null     object
 8   RESULT             68 non-null     object
dtypes: float64(5), object(3), string(1)
memory usage: 6.2+ KB

Dataset Shape:
(86, 9)

Column Names:
['ROLL NO.', 'GENDER ', 'SOFTWARE ENGINEER', 'TOC', 'COMPUTER NETWORK ', 'MACHINE LEARNING ', 'DATA WAREHOUSE ', 'GRADE ', 'RESULT ']

## CHECK MISSING VALUES

Missing values are checked in each column of the dataset.

Identifying missing values is necessary because they may affect statistical calculations and the performance of machine learning algorithms.

In [10]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
ROLL NO.             15
GENDER               14
SOFTWARE ENGINEER    18
TOC                  18
COMPUTER NETWORK     18
MACHINE LEARNING     18
DATA WAREHOUSE       18
GRADE                19
RESULT               18
dtype: int64

In [11]:
print("\nMissing value percentage:")
print((df.isnull().sum() / len(df) * 100).round(2))

Missing value percentage:
ROLL NO.             17.44
GENDER               16.28
SOFTWARE ENGINEER    20.93
TOC                  20.93
COMPUTER NETWORK     20.93
MACHINE LEARNING     20.93
DATA WAREHOUSE       20.93
GRADE                22.09
RESULT               20.93
dtype: float64

In [13]:
# Clean column names by removing leading/trailing spaces

df.columns = df.columns.str.strip()

print("Cleaned column names:")
print(df.columns.tolist())

Cleaned column names:
['ROLL NO.', 'GENDER', 'SOFTWARE ENGINEER', 'TOC', 'COMPUTER NETWORK', 'MACHINE LEARNING', 'DATA WAREHOUSE', 'GRADE', 'RESULT']

In [14]:
subject_columns = [
    "SOFTWARE ENGINEER",
    "TOC",
    "COMPUTER NETWORK",
    "MACHINE LEARNING",
    "DATA WAREHOUSE"
]

for col in subject_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("Subject columns converted to numeric.")

Subject columns converted to numeric.

## HANDLE INVALID OR EMPTY VALUES

The dataset is checked for empty, invalid, or inconsistent entries.

Where required, such values are cleaned or replaced with appropriate values so that the dataset remains consistent and suitable for further processing.

In [15]:
before = len(df)

df = df.dropna(how="all")

after = len(df)

print("Completely empty rows removed:", before - after)
print("New shape:", df.shape)

Completely empty rows removed: 14
New shape: (72, 9)

In [16]:
before = len(df)

df = df.dropna(subset=["ROLL NO."])

df = df.dropna(
    subset=subject_columns,
    how="all"
)

after = len(df)

print("Invalid/empty records removed:", before - after)
print("New shape:", df.shape)

Invalid/empty records removed: 5
New shape: (67, 9)

## HANDLE MISSING VALUES

Missing values in numerical columns are handled using the **mean imputation** technique.

The mean of the valid values in each numerical subject column is calculated and used to replace the missing values.

This helps retain the available records without unnecessarily removing rows from the dataset.

In [17]:
for col in subject_columns:
    mean_value = df[col].mean()
    df[col] = df[col].fillna(mean_value)

print("Missing numerical values filled with subject-wise mean.")

Missing numerical values filled with subject-wise mean.

In [18]:
print("Missing values after mean imputation:")
print(df.isnull().sum())

Missing values after mean imputation:
ROLL NO.             0
GENDER               0
SOFTWARE ENGINEER    0
TOC                  0
COMPUTER NETWORK     0
MACHINE LEARNING     0
DATA WAREHOUSE       0
GRADE                1
RESULT               0
dtype: int64

In [19]:
print("Current dataset shape:", df.shape)

display(df.head(15))

Current dataset shape: (67, 9)

,ROLL NO.,GENDER,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT
0,240104010001,M,30.0,30.0,30.0,30.0,30.0,C,PASS
1,240104010002,F,30.0,40.0,45.0,40.0,35.0,B,Pass
2,240104010003,M,38.0,38.0,38.0,38.0,38.0,B,Pass
3,240104010004,M,59.0,55.0,57.0,58.0,54.0,A,pass
4,240104010005,M,30.0,30.0,30.0,30.0,30.0,C,Pass
5,240104010006,M,40.0,40.0,30.0,40.0,40.0,C,Pass
6,240104010007,F,30.0,30.0,30.0,30.0,30.0,P,pass
7,240104010008,M,30.0,40.0,30.0,40.0,40.0,B,pass
8,240104010001,M,30.0,40.0,25.0,40.0,20.0,P,Pass
9,240104010001,M,25.0,25.0,25.0,25.0,25.0,P,Pass
10,240104010001,M,35.0,35.0,35.0,35.0,35.0,C,Pass
12,2401040100012,F,40.0,45.0,45.0,35.0,35.0,B,Pass
14,240104010014,F,59.0,59.0,59.0,60.0,60.0,O,Pass
15,240104010015,MALE,45.0,47.0,50.0,40.0,55.0,A,pass
16,240104010001,M,56.0,41.0,48.0,29.0,45.0,B,PASS

In [20]:
print("\nDataset information after preprocessing:")
df.info()

Dataset information after preprocessing:
<class 'pandas.core.frame.DataFrame'>
Index: 67 entries, 0 to 85
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ROLL NO.           67 non-null     string
 1   GENDER             67 non-null     object
 2   SOFTWARE ENGINEER  67 non-null     float64
 3   TOC                67 non-null     float64
 4   COMPUTER NETWORK   67 non-null     float64
 5   MACHINE LEARNING   67 non-null     float64
 6   DATA WAREHOUSE     67 non-null     float64
 7   GRADE              66 non-null     object
 8   RESULT             67 non-null     object
dtypes: float64(5), object(3), string(1)
memory usage: 5.2+ KB

## DETECT AND HANDLE OUTLIERS

Outliers are observations that differ significantly from the general pattern of the data.

The numerical subject columns are examined for unusually high or low values. An observed maximum value is checked against the valid marks range before deciding whether it represents a genuine observation or an error.

Valid observations are not removed simply because they are relatively high or low.

In [22]:
# Check for invalid marks outside the valid range 0–60

for col in subject_columns:
    invalid = df[(df[col] < 0) | (df[col] > 60)][["ROLL NO.", col]]
    
    if not invalid.empty:
        print(f"\nInvalid values in {col}:")
        display(invalid)

Invalid values in SOFTWARE ENGINEER:

        ROLL NO.  SOFTWARE ENGINEER
57  240104010056               64.0
62  240104010061              -10.0

Invalid values in TOC:

        ROLL NO.   TOC
33  240104010032  63.0
57  240104010056  99.0
62  240104010061 -20.0

Invalid values in COMPUTER NETWORK:

        ROLL NO.  COMPUTER NETWORK
57  240104010056              87.0
62  240104010061             -15.0

Invalid values in MACHINE LEARNING:

        ROLL NO.  MACHINE LEARNING
33  240104010032              99.0
57  240104010056              93.0
62  240104010061             -60.0

Invalid values in DATA WAREHOUSE:

        ROLL NO.  DATA WAREHOUSE
24  240104010024            61.0
47  240104010046            67.0
57  240104010056            97.0
62  240104010061            -2.0

In [23]:
# Calculate mean using only valid marks (0 to 60)

valid_means = {}

for col in subject_columns:
    valid_values = df.loc[
        (df[col] >= 0) & (df[col] <= 60),
        col
    ]
    
    valid_means[col] = valid_values.mean()

print("Mean of valid marks for each subject:\n")

for col, mean in valid_means.items():
    print(f"{col}: {mean:.2f}")

Mean of valid marks for each subject:

SOFTWARE ENGINEER: 42.34
TOC: 42.92
COMPUTER NETWORK: 42.86
MACHINE LEARNING: 43.19
DATA WAREHOUSE: 43.06

In [24]:
# Replace invalid marks (<0 or >60) with the mean of valid marks

for col in subject_columns:
    mean_value = valid_means[col]
    
    invalid_mask = (df[col] < 0) | (df[col] > 60)
    
    df.loc[invalid_mask, col] = mean_value

print("Invalid marks replaced with subject-wise valid mean.")

Invalid marks replaced with subject-wise valid mean.

In [25]:
print("Checking for invalid marks after replacement:\n")

for col in subject_columns:
    invalid_count = ((df[col] < 0) | (df[col] > 60)).sum()
    
    print(f"{col}: {invalid_count} invalid values")

Checking for invalid marks after replacement:

SOFTWARE ENGINEER: 0 invalid values
TOC: 0 invalid values
COMPUTER NETWORK: 0 invalid values
MACHINE LEARNING: 0 invalid values
DATA WAREHOUSE: 0 invalid values

In [26]:
# Display records containing the previously invalid marks

invalid_roll_numbers = [
    "240104010056",
    "240104010032",
    "240104010061",
    "240104010024",
    "240104010046"
]

display(
    df[df["ROLL NO."].isin(invalid_roll_numbers)]
)

,ROLL NO.,GENDER,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT
24,240104010024,Female,60.000000,58.000000,60.000000,59.0000,43.063492,O,Pass
33,240104010032,Male,33.000000,42.921875,56.000000,43.1875,48.000000,B,Pass
47,240104010046,Mens,0.000000,1.000000,2.000000,3.0000,43.063492,O,Fail
57,240104010056,FEMALE,42.338462,42.921875,42.861538,43.1875,43.063492,O+,PASS
62,240104010061,M,42.338462,42.921875,42.861538,43.1875,43.063492,F,Discharge

## CLEAN CATEGORICAL DATA

Categorical columns are examined for inconsistent or unwanted values.

The **GENDER** column is cleaned and standardized so that only valid categorical values are retained.

After cleaning, the unique gender values are checked to ensure consistency.

In [27]:
# Clean and standardize gender values

df["GENDER"] = df["GENDER"].str.strip().str.upper()

gender_mapping = {
    "M": "M",
    "MALE": "M",
    "MEN": "M",
    "MENS": "M",
    "F": "F",
    "FEMALE": "F"
}

df["GENDER"] = df["GENDER"].map(gender_mapping)

print("Gender values after cleaning:")
print(df["GENDER"].value_counts())

Gender values after cleaning:
GENDER
M    42
F    25
Name: count, dtype: int64

In [28]:
print("Unique Gender values:")
print(df["GENDER"].unique())

Unique Gender values:
['M' 'F']

## PROCESS GRADE AND RESULT

The **GRADE** and **RESULT** columns are retained as part of the dataset.

Where their values need to be generated or corrected, they are assigned according to the specified grading criteria and result conditions based on the students' marks.

This ensures that the final dataset contains consistent and meaningful grade and result information.

In [29]:
# Calculate average marks across all five subjects

df["average_marks"] = df[subject_columns].mean(axis=1)

display(
    df[["ROLL NO."] + subject_columns + ["average_marks"]].head(10)
)

,ROLL NO.,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,average_marks
0,240104010001,30.0,30.0,30.0,30.0,30.0,30.0
1,240104010002,30.0,40.0,45.0,40.0,35.0,38.0
2,240104010003,38.0,38.0,38.0,38.0,38.0,38.0
3,240104010004,59.0,55.0,57.0,58.0,54.0,56.6
4,240104010005,30.0,30.0,30.0,30.0,30.0,30.0
5,240104010006,40.0,40.0,30.0,40.0,40.0,38.0
6,240104010007,30.0,30.0,30.0,30.0,30.0,30.0
7,240104010008,30.0,40.0,30.0,40.0,40.0,36.0
8,240104010001,30.0,40.0,25.0,40.0,20.0,31.0
9,240104010001,25.0,25.0,25.0,25.0,25.0,25.0

In [30]:
# Recalculate Grade based on average marks

def calculate_grade(average):
    if average >= 54:
        return "O"
    elif average >= 48:
        return "A+"
    elif average >= 42:
        return "A"
    elif average >= 36:
        return "B"
    elif average >= 30:
        return "C"
    elif average >= 24:
        return "P"
    else:
        return "F"

df["GRADE"] = df["average_marks"].apply(calculate_grade)

print("Grade recalculated successfully.")

Grade recalculated successfully.

In [31]:
# Recalculate Result based on average marks

df["RESULT"] = np.where(
    df["average_marks"] >= 24,
    "PASS",
    "FAIL"
)

print("Result recalculated successfully.")

Result recalculated successfully.

In [32]:
df.drop(columns=["average_marks"], inplace=True)

print("Temporary average column removed.")
print("Current shape:", df.shape)

Temporary average column removed.
Current shape: (67, 9)

In [33]:
print("Grade distribution:")
print(df["GRADE"].value_counts().sort_index())

print("\nResult distribution:")
print(df["RESULT"].value_counts())

display(df)

Grade distribution:
GRADE
A     10
A+     7
B     12
C     13
F      3
O     18
P      4
Name: count, dtype: int64

Result distribution:
RESULT
PASS    64
FAIL     3
Name: count, dtype: int64

,ROLL NO.,GENDER,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT
0,240104010001,M,30.0,30.0,30.0,30.0,30.0,C,PASS
1,240104010002,F,30.0,40.0,45.0,40.0,35.0,B,PASS
2,240104010003,M,38.0,38.0,38.0,38.0,38.0,B,PASS
3,240104010004,M,59.0,55.0,57.0,58.0,54.0,O,PASS
4,240104010005,M,30.0,30.0,30.0,30.0,30.0,C,PASS
...,...,...,...,...,...,...,...,...,...
80,2520104003,F,40.0,30.0,25.0,26.0,28.0,P,PASS
81,2520104004,M,24.0,25.0,26.0,27.0,24.0,P,PASS
83,2520104006,F,30.0,30.0,30.0,30.0,30.0,C,PASS
84,2520104007,F,45.0,40.0,50.0,48.0,46.0,A,PASS
85,2520104008,F,35.0,30.0,40.0,45.0,48.0,B,PASS

In [35]:
# Check for completely duplicate records

duplicate_count = df.duplicated().sum()

print("Number of completely duplicate records:", duplicate_count)

Number of completely duplicate records: 0

In [36]:
# Display completely duplicate records

duplicates = df[df.duplicated(keep=False)]

if duplicates.empty:
    print("No completely duplicate records found.")
else:
    display(duplicates)

No completely duplicate records found.

## FINAL DATA VERIFICATION

After applying all preprocessing techniques, the dataset is checked again to ensure that:

- Missing values have been handled appropriately.
- Categorical values are consistent.
- Duplicate records have been checked.
- Numerical values are valid.
- Grade and result values are correctly assigned.
- The overall dataset structure is maintained.

In [37]:
# FINAL VERIFICATION

print("FINAL DATASET VERIFICATION\n")

# 1. Dataset shape
print("1. Dataset Shape:")
print(df.shape)

# 2. Missing values
print("\n2. Missing Values:")
print(df.isnull().sum())

# 3. Duplicate records
print("\n3. Duplicate Records:")
print(df.duplicated().sum())

# 4. Invalid marks
print("\n4. Invalid Marks:")

for col in subject_columns:
    invalid_count = ((df[col] < 0) | (df[col] > 60)).sum()
    print(f"{col}: {invalid_count}")

# 5. Gender values
print("\n5. Gender Values:")
print(df["GENDER"].unique())

# 6. Grade values
print("\n6. Grade Values:")
print(sorted(df["GRADE"].unique()))

# 7. Result values
print("\n7. Result Values:")
print(df["RESULT"].unique())

# 8. Data types
print("\n8. Data Types:")
print(df.dtypes)

FINAL DATASET VERIFICATION

1. Dataset Shape:
(67, 9)

2. Missing Values:
ROLL NO.             0
GENDER               0
SOFTWARE ENGINEER    0
TOC                  0
COMPUTER NETWORK     0
MACHINE LEARNING     0
DATA WAREHOUSE       0
GRADE                0
RESULT               0
dtype: int64

3. Duplicate Records:
0

4. Invalid Marks:
SOFTWARE ENGINEER: 0
TOC: 0
COMPUTER NETWORK: 0
MACHINE LEARNING: 0
DATA WAREHOUSE: 0

5. Gender Values:
['M' 'F']

6. Grade Values:
['A', 'A+', 'B', 'C', 'F', 'O', 'P']

7. Result Values:
['PASS' 'FAIL']

8. Data Types:
ROLL NO.             string[python]
GENDER                       object
SOFTWARE ENGINEER           float64
TOC                         float64
COMPUTER NETWORK            float64
MACHINE LEARNING            float64
DATA WAREHOUSE              float64
GRADE                        object
RESULT                       object
dtype: object

In [38]:
# Reset index after all row operations

df.reset_index(drop=True, inplace=True)

print("\nIndex reset successfully.")
print("Final shape:", df.shape)

Index reset successfully.
Final shape: (67, 9)

## SAVE THE PREPROCESSED DATASET

The cleaned and preprocessed dataset is saved as an Excel file for future use.

The output file is saved at:

`EXPORTS/Mldata_Preprocessed.xlsx`

The saved file is then loaded again to verify that the preprocessing results have been stored correctly.

In [39]:
# Save the preprocessed dataset
output_path = "EXPORTS/Mldata_Preprocessed.xlsx"

df.to_excel(output_path, index=False)

print(f"Preprocessed dataset saved successfully at: {output_path}")

Preprocessed dataset saved successfully at: EXPORTS/Mldata_Preprocessed.xlsx

In [40]:
# Verify the saved file
df_check = pd.read_excel(output_path)

print("Saved file loaded successfully!")
print("Shape:", df_check.shape)

display(df_check.head())

Saved file loaded successfully!
Shape: (67, 9)

,ROLL NO.,GENDER,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT
0,240104010001,M,30.0,30.0,30.0,30.0,30.0,C,PASS
1,240104010002,F,30.0,40.0,45.0,40.0,35.0,B,PASS
2,240104010003,M,38.0,38.0,38.0,38.0,38.0,B,PASS
3,240104010004,M,59.0,55.0,57.0,58.0,54.0,O,PASS
4,240104010005,M,30.0,30.0,30.0,30.0,30.0,C,PASS

## OBSERVATIONS

- Missing values were identified and appropriately handled.
- Numerical missing values were imputed using the mean of valid observations.
- Duplicate records were checked.
- Categorical values in the **GENDER** column were cleaned and standardized.
- Numerical subject marks were examined for unusual values.
- Grade and result information was processed according to the specified criteria.
- The final cleaned dataset was successfully saved and verified.

## CONCLUSION

The given dataset was successfully preprocessed using appropriate data preprocessing techniques. Missing values, categorical inconsistencies, duplicate records, numerical values, and other data quality issues were examined and handled as required.

The resulting dataset is clean, consistent, and ready for further data analysis or machine learning applications.